### ISSUE TITLE
how to obtain raw data from various databases, especially from Pathbank

### ISSUE THREAD

**Issue by Tiantao2000** [rxn4chemistry/biocatalysis-model#6]
Hello, nice job. I want to know how to obtain raw data from databases （especially from Pathbank）. Thank you !!

**Comment by drugilsberg** [comment]
Hey @Yoko1030 thanks for the interest in our work, all the databases have their own way to grant access to the raw data.
For example PathBank offers various formats (https://pathbank.org/downloads).
I recommend checking the links we report [here](https://github.com/rxn4chemistry/biocatalysis-model#data-sources) and chose the option that is more suited for your use case/tooling.
